"""added creator_id to f flight

Revision ID: 5455c45e8c3f
Revises: f4696779328e
Create Date: 2021-11-25 10:31:51.071648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5455c45e8c3f'
down_revision = 'f4696779328e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flights', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'flights', 'flasklogin-users', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'flights', type_='foreignkey')
    op.drop_column('flights', 'creator_id')
    # ### end Alembic commands ###
