"""added aircraft type to flights model

Revision ID: aeb12cebf100
Revises: ed945a83f1ef
Create Date: 2021-11-18 11:57:49.420342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeb12cebf100'
down_revision = 'ed945a83f1ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flights', sa.Column('aircraft_type', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flights', 'aircraft_type')
    # ### end Alembic commands ###
