"""first migrate

Revision ID: bbc1d5b15de2
Revises: 
Create Date: 2021-11-18 16:28:48.797054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbc1d5b15de2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flasklogin-users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('flights',
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('flight_no', sa.String(length=10), nullable=False),
    sa.Column('aircraft_type', sa.String(length=20), nullable=True),
    sa.Column('aircraft_call_letters', sa.String(length=10), nullable=True),
    sa.Column('flight_date', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('flight_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flights')
    op.drop_table('flasklogin-users')
    # ### end Alembic commands ###
