"""fix aerial typo

Revision ID: d54461042eeb
Revises: a44db282da3d
Create Date: 2021-12-18 10:17:59.872334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd54461042eeb'
down_revision = 'a44db282da3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pilot', sa.Column('aerial_application_rating', sa.Boolean(), server_default='False', nullable=True))
    op.drop_column('pilot', 'ariel_application_rating')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pilot', sa.Column('ariel_application_rating', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.drop_column('pilot', 'aerial_application_rating')
    # ### end Alembic commands ###
