"""Initial migration

Revision ID: ed945a83f1ef
Revises: 
Create Date: 2021-11-18 11:47:54.975485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed945a83f1ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flasklogin-users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('flights',
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('flight_no', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('flight_id')
    )
    op.drop_table('pilots')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pilots',
    sa.Column('pilot_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pilot_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('pilot_id', name='pilots_pkey')
    )
    op.drop_table('flights')
    op.drop_table('flasklogin-users')
    # ### end Alembic commands ###
