"""initial commit third try

Revision ID: f4696779328e
Revises: 
Create Date: 2021-11-20 15:31:19.200362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4696779328e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flasklogin-users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('is_superadmin', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('has_image', sa.Boolean(), server_default='False', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('flights',
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('aircraft_type', sa.String(length=20), server_default='Wright Flyer', nullable=True),
    sa.Column('aircraft_rego', sa.String(length=10), server_default='AAAA', nullable=True),
    sa.Column('flight_date', sa.String(length=10), server_default='1/1/1900', nullable=False),
    sa.Column('pilot_in_command', sa.String(length=100), nullable=False),
    sa.Column('other_crew', sa.String(length=200), nullable=True),
    sa.Column('details', sa.String(length=200), nullable=False),
    sa.Column('single_engine_icus_day', sa.Float(), nullable=True),
    sa.Column('single_engine_icus_night', sa.Float(), nullable=True),
    sa.Column('single_engine_dual_day', sa.Float(), nullable=True),
    sa.Column('single_engine_dual_night', sa.Float(), nullable=True),
    sa.Column('single_engine_command_day', sa.Float(), nullable=True),
    sa.Column('single_engine_command_night', sa.Float(), nullable=True),
    sa.Column('multi_engine_icus_day', sa.Float(), nullable=True),
    sa.Column('multi_engine_icus_night', sa.Float(), nullable=True),
    sa.Column('multi_engine_dual_day', sa.Float(), nullable=True),
    sa.Column('multi_engine_dual_night', sa.Float(), nullable=True),
    sa.Column('multi_engine_command_day', sa.Float(), nullable=True),
    sa.Column('multi_engine_command_night', sa.Float(), nullable=True),
    sa.Column('multi_engine_co_pilot_day', sa.Float(), nullable=True),
    sa.Column('multi_engine_co_pilot_night', sa.Float(), nullable=True),
    sa.Column('instrument_in_flight', sa.Float(), nullable=True),
    sa.Column('instrument_ground', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('flight_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flights')
    op.drop_table('flasklogin-users')
    # ### end Alembic commands ###
